AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] # as per VGG 16 model refer keras website
BATCH_SIZE: 16
INCLUDE_TOP: False #droping the dense Layer from VGG model
EPOCHS: 4
CLASSES: 2
WEIGHTS: imagenet
LEARNING_RATE: 0.03